version: '2'
services:
  rancher-active-proxy:
    image: adi90x/rancher-active-proxy
    environment:
      DEBUG: 'false'
      CRON: 0 */3 * * *
    stdin_open: true
    volumes:
    - ./htpasswd:/etc/nginx/htpasswd
    - ./vhost.d:/etc/nginx/vhost.d
    - ./letsencrypt:/etc/letsencrypt
    tty: true
    ports:
    - 80:80/tcp
    - 443:443/tcp
    labels:
      io.rancher.container.pull_image: always
