version: '2'
services:
  postgresql:
    image: sameersbn/postgresql:9.6-2
    environment:
      DB_EXTENSION: pg
      DB_NAME: gitlabhq_production
      DB_PASS: password
      DB_USER: user
    volumes:
    - ./postgresql:/var/lib/postgresql:Z
  gitlab:
    image: sameersbn/gitlab:10.2.2
    environment:
      DB_ADAPTER: postgresql
      DB_HOST: postgresql
      DB_NAME: gitlabhq_production
      DB_PASS: password
      DB_PORT: '5432'
      DB_USER: user
      DEBUG: 'false'
      GITLAB_BACKUP_SCHEDULE: daily
      GITLAB_BACKUP_TIME: 01:00
      GITLAB_EMAIL: mail@example.domain
      GITLAB_EMAIL_REPLY_TO: mail@example.domain
      GITLAB_HOST: localhost
      GITLAB_HTTPS: 'false'
      GITLAB_INCOMING_EMAIL_ADDRESS: reply@example.com
      GITLAB_NOTIFY_ON_BROKEN_BUILDS: 'true'
      GITLAB_NOTIFY_PUSHER: 'false'
      GITLAB_PORT: '10080'
      GITLAB_RELATIVE_URL_ROOT: ''
      GITLAB_ROOT_EMAIL: mail@example.domain
      GITLAB_ROOT_PASSWORD: root_password
      GITLAB_SECRETS_DB_KEY_BASE: db_key_base
      GITLAB_SECRETS_OTP_KEY_BASE: otp_key_base
      GITLAB_SECRETS_SECRET_KEY_BASE: secret_key_base
      GITLAB_SSH_PORT: '10022'
      GITLAB_TIMEZONE: Berlin
      LETSENCRYPT_EMAIL: mail@example.domain
      LETSENCRYPT_HOST: gitlab.example.domain
      REDIS_HOST: redis
      REDIS_PORT: '6379'
      SSL_SELF_SIGNED: 'false'
      TZ: Europe/Berlin
      VIRTUAL_HOST: gitlab.example.domain
    volumes:
    - ./gitlab:/home/git/data:Z
    labels:
      rap.le_email: mail@example.domain
      rap.le_host: gitlab.example.domain
      rap.host: gitlab.example.domain
  redis:
    image: sameersbn/redis:latest
    volumes:
    - ./redis:/var/lib/redis:Z
    command:
    - --loglevel warning
